# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import imageupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to=imageupload.models.scrable_uploaded_filename, verbose_name='uploaded_image'),
        ),
    ]
